"""empty message

Revision ID: 193c76811721
Revises: 7f0a706ae85f
Create Date: 2023-11-06 10:37:25.588392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193c76811721'
down_revision = '7f0a706ae85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('document_title', sa.String(length=150), nullable=False),
    sa.Column('change_descritption', sa.String(length=150), nullable=False),
    sa.Column('change_justify', sa.String(length=150), nullable=False),
    sa.Column('type_document', sa.Enum('formulario', 'procedimiento', 'instrucciont', 'otro', name='type_document'), nullable=True),
    sa.Column('change_type', sa.Enum('creacion', 'actualizacion', 'eliminacion', name='change_type'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_descritption'),
    sa.UniqueConstraint('change_justify'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('document_title'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petitions')
    # ### end Alembic commands ###
