"""empty message

Revision ID: 2e6540195b7f
Revises: c5f2c9e9d9a9
Create Date: 2023-11-03 15:29:58.204212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6540195b7f'
down_revision = 'c5f2c9e9d9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.Enum('usuario', 'calidad', 'admin', name='role'), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'usuario'::character varying"), autoincrement=False, nullable=True))
        batch_op.drop_column('roles')

    # ### end Alembic commands ###
