"""empty message

Revision ID: 3711e6e28d4e
Revises: be17673710ac
Create Date: 2023-11-23 16:02:52.921745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3711e6e28d4e'
down_revision = 'be17673710ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_column('p_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.drop_column('created')

    # ### end Alembic commands ###
