"""empty message

Revision ID: 4900a0879407
Revises: e65c87e96be1
Create Date: 2023-11-02 16:49:42.167629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4900a0879407'
down_revision = 'e65c87e96be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('USUARIO', 'CALIDAD', 'ADMIN', name='role'), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
