"""empty message

Revision ID: 761d020cc16d
Revises: e7aa1b34adf3
Create Date: 2023-11-06 13:02:01.735479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761d020cc16d'
down_revision = 'e7aa1b34adf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petitions', schema=None) as batch_op:
        batch_op.drop_constraint('petitions_change_description_key', type_='unique')
        batch_op.drop_constraint('petitions_change_justify_key', type_='unique')
        batch_op.drop_constraint('petitions_code_key', type_='unique')
        batch_op.drop_constraint('petitions_document_title_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petitions', schema=None) as batch_op:
        batch_op.create_unique_constraint('petitions_document_title_key', ['document_title'])
        batch_op.create_unique_constraint('petitions_code_key', ['code'])
        batch_op.create_unique_constraint('petitions_change_justify_key', ['change_justify'])
        batch_op.create_unique_constraint('petitions_change_description_key', ['change_description'])

    # ### end Alembic commands ###
