"""empty message

Revision ID: 7f0a706ae85f
Revises: 2e6540195b7f
Create Date: 2023-11-03 15:47:21.793001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f0a706ae85f'
down_revision = '2e6540195b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles_user', sa.Enum('usuario', 'calidad', 'admin', name='role'), nullable=True))
        batch_op.drop_column('roles')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', postgresql.ENUM('usuario', 'calidad', 'admin', name='role'), autoincrement=False, nullable=True))
        batch_op.drop_column('roles_user')

    # ### end Alembic commands ###
