"""empty message

Revision ID: 823ad7a4bb1e
Revises: 3711e6e28d4e
Create Date: 2023-12-06 09:49:17.938232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823ad7a4bb1e'
down_revision = '3711e6e28d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('roles_user', sa.Enum('usuario', 'calidad', 'admin', name='role'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('petitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('document_title', sa.String(length=150), nullable=False),
    sa.Column('change_description', sa.String(length=150), nullable=False),
    sa.Column('change_justify', sa.String(length=150), nullable=False),
    sa.Column('type_document', sa.Enum('formulario', 'procedimiento', 'instrucciont', 'otro', name='type_document'), nullable=True),
    sa.Column('change_type', sa.Enum('creacion', 'actualizacion', 'eliminacion', name='change_type'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('petition_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_petition', sa.DateTime(timezone=True), nullable=False),
    sa.Column('process_affected', sa.String(length=100), nullable=False),
    sa.Column('name_customer', sa.String(length=100), nullable=False),
    sa.Column('process_customer', sa.String(length=100), nullable=False),
    sa.Column('date_petition_sent', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('divulgado', 'distribuido', 'completado', name='status'), nullable=True),
    sa.Column('date_petition_received', sa.String(length=100), nullable=False),
    sa.Column('date_finished_petition', sa.String(length=100), nullable=False),
    sa.Column('observation', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('petition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['petition_id'], ['petitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petition_control')
    op.drop_table('petitions')
    op.drop_table('user_table')
    # ### end Alembic commands ###
