"""empty message

Revision ID: 8fe809d00a0f
Revises: 9f94b7a76520
Create Date: 2023-11-23 11:41:11.031023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fe809d00a0f'
down_revision = '9f94b7a76520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition_control', schema=None) as batch_op:
        batch_op.alter_column('date_petition',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition_control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('divulgado', 'distribuido', 'completado', name='status'), autoincrement=False, nullable=True))
        batch_op.alter_column('date_petition',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
