"""empty message

Revision ID: 9f94b7a76520
Revises: dfecfb8ecc89
Create Date: 2023-11-22 12:43:18.528569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f94b7a76520'
down_revision = 'dfecfb8ecc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition_control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('petition_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'petitions', ['petition_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition_control', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('petition_id')

    # ### end Alembic commands ###
