"""empty message

Revision ID: aadd5bcbd99d
Revises: 8fe809d00a0f
Create Date: 2023-11-23 11:58:11.133447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadd5bcbd99d'
down_revision = '8fe809d00a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition_control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('divulgado', 'distribuido', 'completado', name='status'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition_control', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
