"""empty message

Revision ID: d60fa2c094b0
Revises: aadd5bcbd99d
Create Date: 2023-11-23 12:08:29.361836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60fa2c094b0'
down_revision = 'aadd5bcbd99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition_control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition_control', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
