"""empty message

Revision ID: e7aa1b34adf3
Revises: 193c76811721
Create Date: 2023-11-06 11:04:30.262709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7aa1b34adf3'
down_revision = '193c76811721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_description', sa.String(length=150), nullable=False))
        batch_op.drop_constraint('petitions_change_descritption_key', type_='unique')
        batch_op.create_unique_constraint(None, ['change_description'])
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('change_descritption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_descritption', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('petitions_change_descritption_key', ['change_descritption'])
        batch_op.drop_column('change_description')

    # ### end Alembic commands ###
